import {
  AlertCircle,
  AppWindow,
  ArrowRight,
  Award,
  BadgeCheck,
  Bold,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarClock,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDollarSign,
  ClipboardList,
  Clock,
  Droplets,
  Eye,
  Facebook,
  FileText,
  Globe,
  GraduationCap,
  Handshake,
  HardHat,
  Heading2,
  Heading3,
  HeartHandshake,
  Home,
  Image,
  Inbox,
  Instagram,
  Italic,
  KeyRound,
  LayoutGrid,
  Link2,
  List,
  ListOrdered,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MoveHorizontal,
  Pencil,
  Phone,
  Quote,
  RotateCcw,
  Scale,
  Search,
  Send,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sofa,
  Sparkles,
  SprayCan,
  Star,
  Store,
  Target,
  ThumbsUp,
  Trash2,
  Users,
  X,
  type LucideProps,
} from "lucide-react";

/**
 * Every icon used anywhere on the site, listed by name.
 * data/content.ts refers to these names as plain strings, which keeps the
 * content file free of imports and easy to edit.
 */
const icons = {
  AlertCircle,
  AppWindow,
  ArrowRight,
  Award,
  BadgeCheck,
  Bold,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarClock,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDollarSign,
  ClipboardList,
  Clock,
  Droplets,
  Eye,
  Facebook,
  FileText,
  Globe,
  GraduationCap,
  Handshake,
  HardHat,
  Heading2,
  Heading3,
  HeartHandshake,
  Home,
  Image,
  Inbox,
  Instagram,
  Italic,
  KeyRound,
  LayoutGrid,
  Link2,
  List,
  ListOrdered,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MoveHorizontal,
  Pencil,
  Phone,
  Quote,
  RotateCcw,
  Scale,
  Search,
  Send,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sofa,
  Sparkles,
  SprayCan,
  Star,
  Store,
  Target,
  ThumbsUp,
  Trash2,
  Users,
  X,
};

export type IconName = keyof typeof icons;

type IconProps = LucideProps & {
  /** Name of the icon, e.g. "Sparkles". Falls back to a sparkle if unknown. */
  name: string;
};

export default function Icon({ name, ...props }: IconProps) {
  const Component = icons[name as IconName] ?? Sparkles;
  return <Component aria-hidden="true" {...props} />;
}
